spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8

  mail:
    host: smtp.qq.com
    username: 969064814@qq.com
    password: pwojcehlfxqsbcig
    default-encoding: utf-8

  freemarker:
    cache: false




