spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8



  mail:
    host: smtp.qq.com
    username: 2576047818@qq.com
    password: yrcutmkpbdrjebec
    default-encoding: utf-8


  thymeleaf:
    cache: false
    mode: HTML


mybatis-plus:
  type-aliases-package: problog.entity
  mapper-locations: classpath:templates/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



server:
  port: 8080

